allowed_patterns:
  - "EXAMPLE_ACCESS_KEY_ID"
  - "EXAMPLE_AWS_REGION"
  - "EXAMPLE_SECRET_ACCESS_KEY"
  - "EXAMPLE_SESSION_TOKEN"
  - "YOUR_AWS_REGION"
  - "YOUR_ACCESS_KEY_ID"
  - "YOUR_SECRET_ACCESS_KEY"
  - "YOUR_SESSION_TOKEN"
  - "EXAMPLE_USER_ID"
  - "FAKE_ARN_123"
  - "SUBSCRIPTION_ID_SUBSCRIPTION_ID"
  - "TENANT_ID_TENANT_ID_TENANT_ID"
  - "SP_APP_ID_SP_APP_ID"
  - "SP_PASSWORD_SP_PASSWORD"
  - "SP_TENANT_SP_TENANT"
  - "AZURE_LOCATION"
  - "OS_AUTH_URL"
  - "OS_APPLICATION_CREDENTIAL_ID"
  - "OS_APPLICATION_CREDENTIAL_SECRET"
  - "OS_REGION_NAME"
  - "OS_IDENTITY_API_VERSION"
  - "OS_AUTH_TYPE"
  - "VSPHERE_SERVER"
  - "VSPHERE_THUMBPRINT"
  - "VSPHERE_DATACENTER"
  - "VSPHERE_DATASTORE"
  - "VSPHERE_RESOURCEPOOL"
  - "VSPHERE_FOLDER"
  - "VSPHERE_CONTROL_PLANE_ENDPOINT"
  - "VSPHERE_SSH_KEY"
  - "VSPHERE_VM_TEMPLATE"
  - "VSPHERE_NETWORK"
  - "EXAMPLE_OKTA_APP_CLIENT_ID"
  - "EXAMPLE_OKTA_APP_CLIENT_SECRET"
  - "PRIVATE_SSH_KEY_B64"
  - "GCP_PROJECT_ID"
  - "GCP_PRIVATE_KEY_ID"
  - "GCP_PRIVATE_KEY"
  - "GCP_CLIENT_ID"
  - "GCP_B64ENCODED_CREDENTIALS"
  - "SFDC_AUTH_URL"
  - "SFDC_USERNAME"
  - "SFDC_PASSWORD"
  - "SFDC_ORGANIZATION_ID"
  - "SFDC_ENVIRONMENT_ID"
  - "GITHUB_USERNAME"
  - "GITHUB_TOKEN"
  - "BASE64_ENCODED_BMC_USERNAME"
  - "BASE64_ENCODED_BMC_PASSWORD"
