site_name: Documentation
site_description: Documentation for Mirantis Kubernetes Engine 4
site_author: Mirantis, Inc.

docs_dir: docs/
repo_name: MKE 4 Documentation
repo_url: https://github.com/jjainschigg-r/new-mke-docs
edit_uri: https://github.com/jjainschigg-r/new-mke-docs/edit/main/docs/

copyright:
  Copyright &copy; 2025 Mirantis Inc. - All rights reserved

theme:
  name: "material"
  highlightjs: true
  language: "en"
  custom_dir: docs/custom_theme
  favicon: img/favicon.svg
  logo: img/mke-4k-inverted.svg
  
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - toc.autohide
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.tracking   # Anchor tracking
    - toc.follow            # Sidebar is automatically scrolled so that the active anchor is always visible
    - search.suggest        # Search suggestions
    - search.highlight      # Search highlights all occurrences after following the link
    # - content.action.edit
    - content.action.view
    - navigation.path       # Not working, for sponsors only
    - navigation.indexes
    # - navigation.tabs
    # - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/plausible.js

plugins:
  - search
  - ezglossary:
      section_config:
        - name: demo
          inline_refs: short
  - macros:
      j2_variable_start_string: "{{{"
      j2_variable_end_string: "}}}"
  - exclude:
      glob:
        - "*.etag"
        - Dockerfile.serve-dev
        - Makefile*
        - requirements_pip.txt
        - requirements.txt
  - redirects:
      redirect_maps:
 
nav:
  - MKE 4k Documentation: index.md
  - Concepts:
    - Concepts: concepts/index.md
    - Architecture: concepts/architecture.md
    - Configuration: concepts/configuration.md
    - Container Network Interfaces: concepts/cni.md
    - k0rdent templates: concepts/k0rdent-templates.md
  - Configuration:
    - Configuration: configuration/index.md
    - Authentication:
      - Authentication: configuration/authentication/index.md
      - Basic authentication: configuration/authentication/basic-authentication.md
      - LDAP: configuration/authentication/LDAP.md
      - OIDC: configuration/authentication/OIDC.md
      - SAML: configuration/authentication/SAML.md
    - Backup and restore:
      - Backup and restore: configuration/backup-restore/index.md
      - Back up etcd: configuration/backup-restore/backup-etcd.md
      - External: configuration/backup-restore/external.md
      - In Cluster: configuration/backup-restore/in-cluster.md
    - Cloud providers:
      - Cloud providers: configuration/cloudproviders/index.md
    - Container Network Interfaces:
      - Container Network Interfaces: configuration/container-network-interface/index.md
      - Unmanaged CNI Providers:
        - Unmanaged CNI Providers: configuration/container-network-interface/unmanaged-cni-providers/index.md
        - Configure time windows for network bootstrapping: configuration/container-network-interface/unmanaged-cni-providers/configure-time-windows-bootstrapping.md
        - Considerations and Best Practices: configuration/container-network-interface/unmanaged-cni-providers/considerations-best-practices.md
        - Install an unmanaged CNI plugin: configuration/container-network-interface/unmanaged-cni-providers/install-unmanaged-cni.md
        - Limitations: configuration/container-network-interface/unmanaged-cni-providers/limitations-unmanaged-cni.md
        - Network policies: configuration/container-network-interface/unmanaged-cni-providers/network-policies.md
        - Prerequisites for unmanaged CNI on MKE 4k: configuration/container-network-interface/unmanaged-cni-providers/prerequisites-unmanaged-cni.md
        - Verify CNI plugin installation: configuration/container-network-interface/unmanaged-cni-providers/verify-installation.md
      - Calico OSS: configuration/container-network-interface/configure-cni-providers.md
      - CNI Configuration Example: configuration/container-network-interface/cni-configuration-example.md
      - Enable CNI Providers: configuration/container-network-interface/enable-cni-providers.md
      - Limitations: configuration/container-network-interface/cni-limitations.md
      - Network Configuration: configuration/container-network-interface/network-configuration.md
    - Ingress controller:
      - Ingress controller: configuration/ingress/index.md
      - TCP and UDP services: configuration/ingress/tcp-udp-services.md
    - Kubernetes components:
      - Kubernetes components: configuration/kubernetes/index.md
      - Audit logging: configuration/kubernetes/audit-logging.md
      - etcd: configuration/kubernetes/etcd.md
      - kube-apiserver: configuration/kubernetes/kube-apiserver.md
      - kube-controller-manager: configuration/kubernetes/kube-controller-manager.md
      - kube-scheduler: configuration/kubernetes/kube-scheduler.md
      - kubelet: configuration/kubernetes/kubelet.md
    - MetalLB load balancer:
      - MetalLB load balancer: configuration/metallb/index.md
    - Node Feature Discovery (NFD):
      - Node Feature Discovery (NFD): configuration/node-feature-discovery/index.md
    - Policy Controller:
      - Policy Controller: configuration/policycontroller/index.md
      - OPA Gatekeeper: configuration/policycontroller/opagatekeeper.md
    - Add services: configuration/add-services.md
    - Configuration Drift Detection: configuration/configuration-drift-detection.md
    - CoreDNS Lameduck: configuration/coredns-lameduck.md
    - MKE 4k Dashboard: configuration/mke4k-dashboard.md
    - Monitoring: configuration/monitoring.md
    - Multus: configuration/multus.md
    - NVIDIA GPU Workloads: configuration/nvidia-gpu.md
    - Support Bundle: configuration/support-bundle.md
    - Telemetry: configuration/telemetry.md
    - TLS certificates: configuration/tlscertificates.md
    - Workload node deployment: configuration/workload-node-deployment.md
  - Downloads:
    - Oss Licenses:
  - Getting started:
    - Getting started: getting-started/index.md
    - Licensing MKE 4k:
      - Licensing MKE 4k: getting-started/licensing-mke4/index.md
      - Apply an MKE 4k license following installation: getting-started/licensing-mke4/apply-mke4k-license-post-installation.md
      - Obtain your MKE 4k license: getting-started/licensing-mke4/obtain-mke4k-license.md
      - Set your license in the configuration: getting-started/licensing-mke4/set-license-in-configuration.md
    - Access and manage the cluster with kubectl: getting-started/access-manage-cluster-kubectl.md
    - Add and remove cluster nodes: getting-started/add-and-remove-cluster-nodes.md
    - Create a cluster: getting-started/create-cluster.md
    - Install the MKE 4k CLI: getting-started/install-MKE-4k-CLI.md
    - Login to the registry: getting-started/offline-installation.md
    - Obtain the current MKE 4k configuration file: getting-started/get-current-mke-config.md
    - Start interacting with the cluster: getting-started/start-interacting-with-cluster.md
    - System requirements: getting-started/system-requirements.md
    - Uninstall a cluster: getting-started/uninstall-cluster.md
  - Release notes:
    - Release notes: release-notes/index.md
    - 4.1.0:
      - 4.1.0: release-notes/4.1.0/index.md
      - Addressed issues: release-notes/4.1.0/addressed-issues.md
      - Enhancements: release-notes/4.1.0/enhancements.md
      - Known issues: release-notes/4.1.0/known-issues.md
      - Middleware component versions: release-notes/4.1.0/major-component-versions.md
    - Features Summary: release-notes/features-summary.md
  - Tutorials:
    - Tutorials: tutorials/index.md
    - Authentication Provider Setup:
      - "dn: dc=example,dc=org": tutorials/authentication-provider-setup/setting-up-openldap-as-an-ldap-provider.md
      - Setting up Okta as a SAML provider: tutorials/authentication-provider-setup/setting-up-okta-as-a-saml-provider.md
      - Setting up Okta as an OIDC provider: tutorials/authentication-provider-setup/setting-up-okta-as-an-oidc-provider.md
    - Mke4K In Aws:
      - Terraform:
        - Lb Targets:
      - Create a Kubernetes cluster in AWS using Terraform and install MKE 4k: tutorials/mke4k-in-aws/terraform-scenario.md
    - Mke4K Single Node:
      - Mke4K Single Node Scenario: tutorials/mke4k-single-node/mke4k-single-node-scenario.md
  - Upgrade from MKE 3.7 or 3.8:
    - Upgrade from MKE 3.7 or 3.8: upgrade-from-MKE-3x/index.md
    - CoreDNS Lameduck Upgrades: upgrade-from-MKE-3x/coredns-lameduck-upgrades.md
    - Perform the Upgrade: upgrade-from-MKE-3x/perform-migration.md
    - RBAC Upgrades: upgrade-from-MKE-3x/rbac-upgrades.md
    - Revert the Upgrade: upgrade-from-MKE-3x/revert-upgrade.md
    - Troubleshoot the Upgrade: upgrade-from-MKE-3x/troubleshoot-upgrade.md
    - Upgrade Considerations: upgrade-from-MKE-3x/upgrade-considerations.md
    - Upgrade Prerequisites: upgrade-from-MKE-3x/upgrade-prerequisites.md
    - Upgrade the Configuration: upgrade-from-MKE-3x/migrate-configuration.md
    - Upgrade Verification and Access: upgrade-from-MKE-3x/upgrade-verification-access.md
    - Upgrade with cert-manager: upgrade-from-MKE-3x/upgrade-cert-manager.md
    - Upgrade with unmanaged CNI: upgrade-from-MKE-3x/upgrade-unmanaged-cni.md
  - Open Source Components and Licenses: oss-download.md
  - Support, Services, Contact:
    - Overview: support/index.md
    - Get support: https://www.mirantis.com/support/enterprise-support-services/
    - Mirantis CloudCare Portal: https://support.mirantis.com/s/login/
    - Contact us: https://www.mirantis.com/contact/


markdown_extensions:
  - callouts
  - tables
  - pymdownx.details
  - pymdownx.highlight: {}
  - pymdownx.superfences: {}
  - pymdownx.inlinehilite: {}
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
      toc_depth: 3
  - def_list

extra:
  repo_url: https://github.com/jjainschigg-r/new-mke-docs
  docs_repo_name: Mirantis/docs
  generator: false
  base_url: ""
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/MirantisIT
      name: Mirantis on X
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/mirantisus
      name: Mirantis on YouTube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mirantis
      name: Mirantis on LinkedIn
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/MirantisUS
      name: Mirantis on Facebook
  version:
    provider: mike
    default: stable
  analytics:
  docsVersionInfo:
    k0rdentName: Mirantis k0rdent Enterprise
    k0rdentVersion: 1-1-0
    k0rdentDotVersion: 1.1.0
    ociRegistry: oci://registry.mirantis.com/k0rdent-enterprise/charts/k0rdent-enterprise
    k0rdentDigestValue: sha256:3645c61d59e88143e58a7050ca5b2601f5f5810f1eff163ddba74d1477cdc08c
    k0rdentDigestDate: Wed Aug 13 2025 08:42:36 2025
    k0rdentTagList: https://github.com/k0rdent/k0rdent-enterprise/tags
    kofVersions:
      kofDotVersion: 1.1.0
    providerVersions:
      dashVersions:
        clusterApi: 1-0-4
        clusterApiProviderAws: 1-0-3
        clusterApiProviderAzure: 1-0-3
        clusterApiProviderDocker: 1-0-2
        clusterApiProviderGcp: 1-0-3
        clusterApiProviderOpenstack: 1-0-3
        clusterApiProviderVsphere: 1-0-2
        clusterApiProviderIpam: 1-0-2
        clusterApiProviderInfoblox: 1-0-1
        k0smotron: 1-0-6
        adoptedCluster: 1-0-1
        awsEksCluster: 1-0-2
        awsHostedCpCluster: 1-0-11
        awsStandaloneCpCluster: 1-0-12
        azureAksCluster: 1-0-1
        azureHostedCpCluster: 1-0-13
        azureStandaloneCpCluster: 1-0-13
        dockerHostedCpCluster: 1-0-2
        gcpGkeCluster: 1-0-3
        gcpHostedCpCluster: 1-0-12
        gcpStandaloneCpCluster: 1-0-12
        openstackHostedCpCluster: 1-0-2
        openstackStandaloneCpCluster: 1-0-11
        remoteCluster: 1-0-9
        vsphereHostedCpCluster: 1-0-10
        vsphereStandaloneCpCluster: 1-0-11
        sveltosProvider: 0-57-2
      dotVersions:
        clusterApi: 1.0.4
        clusterApiProviderAws: 1.0.3
        clusterApiProviderAzure: 1.0.3
        clusterApiProviderDocker: 1.0.2
        clusterApiProviderGcp: 1.0.3
        clusterApiProviderOpenstack: 1.0.3
        clusterApiProviderVsphere: 1.0.2
        clusterApiProviderIpam: 1.0.2
        clusterApiProviderInfoblox: 1.0.1
        k0smotron: 1.0.6
        adoptedCluster: 1.0.1
        awsEksCluster: 1.0.2
        awsHostedCpCluster: 1.0.11
        awsStandaloneCpCluster: 1.0.12
        azureAksCluster: 1.0.1
        azureHostedCpCluster: 1.0.13
        azureStandaloneCpCluster: 1.0.13
        dockerHostedCpCluster: 1.0.2
        gcpGkeCluster: 1.0.3
        gcpHostedCpCluster: 1.0.12
        gcpStandaloneCpCluster: 1.0.12
        openstackHostedCpCluster: 1.0.2
        openstackStandaloneCpCluster: 1.0.11
        remoteCluster: 1.0.9
        vsphereHostedCpCluster: 1.0.10
        vsphereStandaloneCpCluster: 1.0.11
        sveltosProvider: 0.57.2
    servicesVersions:
      dashVersions:
        certManager: 1-17-1  
        externalSecrets: 0-11-0
        ingressNginx: 4-11-3   
        kyverno: 3-2-6       
        velero: 8-1-0   
      dotVersions:
        certManager: 1.17.1  
        externalSecrets: 0.11.0
        ingressNginx: 4.11.3   
        kyverno: 3.2.6       
        velero: 8.1.0  
    addonVersions:
      digests:
        k0rdentUI: sha256:60ab7a9dafff9dc143a1d5d697052408f3cf8b27f53c460700d09668a5eb2c71
        k0rdentUIDate: Sat Jul 26 14:28:03 2025
      dashVersions:
        ceph: 1-0-3
        dex: 0-19-1
        hco: 1-15-1-mira  
        stacklightOperator: 0-1-0
        stacklightChart: 0-1-0-mcp-16
        clusterApiProviderCapm3: 0-2-0
        capm3StandaloneCpCluster: 0-2-0
        k0rdentUI: 1-0-0-rc7
      dotVersions:
        ceph: 1.0.3
        dex: 0.19.1
        hco: 1.15.1-mira    
        stacklightOperator: 0.1.0  
        stacklightChart: 0.1.0-mcp-16
        clusterApiProviderCapm3: 0.2.0
        capm3StandaloneCpCluster: 0.2.0
        k0rdentUI: 1.0.0-rc7

